### ISSUE TITLE
Title of the document...

### ISSUE THREAD

**Issue by iherman** [w3c/did-cbor-note#2]
At present, it says "application/did+cbor v1.0". Besides being unusual, I am not even sure it would not create problem to have it in our TR collection...

I would propose something more human readable:-)

**Comment by msporny** [comment]
> I would propose something more human readable:-)

Other options include:

* CBOR DID Document Representation
* The did+cbor Representation (slightly less human readable)
* CBOR-encoded DID Documents (but what about CBOR-LD?)

Other options...?

**Comment by iherman** [comment]
I am being conservative, and would opt for the first option.

**Comment by msporny** [comment]
We can't use the first option because there are at least two CBOR representations... with at least one of them implemented (did+ld+cbor)... I went with the second option as it was the most accurate human-readable one. 

Fixed in bdcc0521f0266c47569566322525008a1e17696b
